#+TITLE: mpdmacs
#+DESCRIPTION: A lightweight, ergonomic MPD client for Emacs
#+DATE: <2020-09-29 Tue 18:46>
#+AUTODATE: t
#+AUTHOR: sp1ff
#+EMAIL: <sp1ff@pobox.com>
#+OPTIONS: toc:nil org-md-headline-style:setext *:t ^:nil

* Introduction

[[https://github.com/sp1ff/mpdmacs][mpdmacs]] is a lightweight, ergonimic [[https://www.musicpd.org/][MPD]] client for Emacs.

This repository is work-in-progress. I've chosen the version number (0.1) in the hopes of conveying that.

* Prerequisites

Emacs 25.1 & [[https://melpa.org/#/elmpd][elmpd]] latest.

* Installing

I plan on submitting this package to [[https://melpa.org][MELPA]] but for now, it's only available as a tarball. Perform the usual "configure/make/make install" incantations.

* Getting Started

Pull in =mpdmacs= as usual via =require=: =(require 'mpdmacs)=. Configure =mpdmacs= to connect to your MPD server by customizing the variables:

  - =mpdmacs-host= & =mpdmacs-port=: If you're talking over a TCP socket, configure these two variables with the hostname and port number at which MPD is listening
  - =mpd-socket=: If your MPD server is local & listening on a Unix socket, set this variable to its path. If you want to talk over a TCP socket, best to set this to nil (=elmpd-enable=, below, will try the local socket first, if it exists)

At this point, =mpdmacs= has done nothing: you need to explicitly enable it by calling =(mpdmacs-enable)=. This will open a connection to your MPD server, begin monitoring its state for changes, and enable you to begin issuing commands.

=mpdmacs= supplies several interactive commands, with keybindings in =mpdmacs-keymap=; you may want to map a chord you find convenient to that keymap like so:

#+BEGIN_SRC elisp
  (defun my-mpdmacs-hook ()
    (global-set-key "\C-c m" 'mpdmacs-keymap))
  (add-hook 'mpdmacs-load-hook 'my-mpdmacs-hook)
#+END_SRC

If you ever want to turn =mpdmacs= off, you can invoke =(mpdmacs-unload)=.
* Motivation & Philosophy

There are already capable MPD clients out there such as [[https://gitea.petton.fr/mpdel/mpdel][mpdel]] 
& [[https://github.com/emacs-mirror/emacs/blob/master/lisp/mpc.el][mpc]] so why another? I've tried both & like them fine, but they're full-featured MPD clients. I hope that =mpdmacs= will fill a different role, that of an unobtrusive assistant that will assist you with your music while using Emacs for other things. If you want to interact with the current play queue, you would go to one of them. If you want to skip to the next track with a quick key sequence, while showing the current track in the mode line, use =elmpd=.
* Learning More or Contributing

At the time of this writing, =mpdmacs.el= consists of a few hundred lines of code, so if you're looking to customize or hack on it, dive in! Comments, complaints, suggestions & PRs welcome.
* Status & Roadmap

This is a work-in-progress. Interfaces are unstable & may change suddenly.
